spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testcode
    username: postgres
    password: abcd1234
  sql:
    init:
      mode: always



#mybatis:
#  type-aliases-package: com.testcode.apartment

logging:
  level:
    com.testcode.apartment: debug

