server:
  servlet:
    context-path: "/service"
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/todo
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.joc.todo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      type.BasicTypeRegistry: INFO
