server:
  servlet:
    context-path: /service
spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/h2/todo
    url: jdbc:log4jdbc:h2:tcp://localhost/~/h2/todo
    username: sa
    password:
    #    driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none # create
    properties:
      hibernate:
        format_sql: true
# Slf4j 로깅레벨 > TRACE > DEBUG > INFO > WARN > ERROR > FATAL
logging:
  level:
    com.joc.todo: DEBUG
    org.hibernate:
      SQL: DEBUG
      type: TRACE
      type.BasicTypeRegistry: INFO
    jdbc: WARN
#      resultset: DEBUG
